name: Shiftly
options:
  bundleIdPrefix: com.digilix
  minimumXcodeGenVersion: 2.37.0
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  Shiftly:
    type: application
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Sources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.digilix.shiftly
        CODE_SIGN_STYLE: Manual
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    scheme:
      gatherCoverageData: false
